# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: "$(Year:yyyy).$(Month).$(BuildID)-ci"

trigger:
  # to make the ci build more efficient
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#batching-ci-runs
  batch: true
  branches:
    include:
      - main

pr: none

resources:
  repositories:
    - repository: openjdk_azure_devops_harness
      type: git
      name: github_move/openjdk-azure-devops-harness
      ref: refs/heads/main

    - repository: devops_demo
      type: git
      name: github_move/devops_demo
      ref: refs/heads/main

variables:
  JTREG_VERSION: "6.1"

stages:
  - template: /ci_main.yml@devops_demo
