name: Build JDK on Linux

on:
  pull_request:
    branches: 
    - main

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: 'Checkout Source'
      uses: actions/checkout@v3
    
    - name: 'Set up JDK 16'
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
        java-package: jdk
        
    - name: 'Install jtreg'
      run: sudo apt install jtreg
      
    - name: 'Install toolchain and dependencies'
      run: |
        # Install dependencies using apt-get
        sudo apt-get update
        sudo apt-get install --only-upgrade apt
        sudo apt-get install build-essential libxrandr-dev libxtst-dev libcups2-dev libasound2-dev
        
    - name: 'Configure'
      run: >
        bash configure
        --build=x86_64-unknown-linux-gnu
        --openjdk-target=x86_64-unknown-linux-gnu
        
    - name: 'Make'
      run: make images
      
    - name: 'Check for failure'
      id: check
      run: |
        # Check for failure marker file
        build_dir="$(ls -d build/*)"
        if [[ -e $build_dir/build-failure ]]; then
          # Collect relevant log files
          mkdir failure-logs
          cp \
              $build_dir/spec.gmk \
              $build_dir/build.log \
              $build_dir/configure.log \
              $build_dir/make-support/failure-summary.log \
              $build_dir/make-support/failure-logs/* \
              failure-logs/ 2> /dev/null || true
          echo '::set-output name=failure::true'
        fi
      shell: bash

    - name: 'Upload build logs'
      uses: actions/upload-artifact@v3
      with:
        name: failure-logs-linux
        path: failure-logs
      if: steps.check.outputs.failure == 'true'
      
    - name: 'Check Version'
      run: ./build/*/images/jdk/bin/java -version
      
    - name: 'Run Basic Tests'
      run: make run-test-tier1










